config/routes.rb
Rails.application.routes.draw do
  resources :articles

  resources :alerts
  get 'search', to: 'search#search'

  root 'articles#index'

end

app/models/alert.rb
class Alert < ActiveRecord::Base

	validates_presence_of :name, :email, :keyword
end

app/models/article.rb
class Article < ActiveRecord::Base
	include ArticleSearch

	validates_presence_of :title, :text, :author
end

app/models/concerns/article_search.rb
module ArticleSearch
	extend ActiveSupport::Concern

	included do 
		# Setting up ElasticSearch integration
		include Elasticsearch::Model 
		include Elasticsearch::Model::Callbacks 

		#Set Name of Index 
		index_name Rails.application.class.parent_name.underscore 
		document_type self.name.downcase

		#Mapping the document type
		settings index: { number_of_shards: 1 } do 
			mapping dynamic: false do				
				indexes :title, analyzer: 'portuguese' 
				indexes :author 
				indexes :text, analyzer: 'portuguese' 
				indexes :created_at, :type => 'date'
			end 
		end

		#Search Query
		def self.search(query)
	       __elasticsearch__.search(
	        {
	            query: {
	              multi_match: {
	                query: query,
	                fields: ['title^5', 'author', 'text']
	              }
	            },
	            highlight: {
	              pre_tags: ['<em>'],
	              post_tags: ['</em>'],
	              fields: {
	                title: {},
	                author: {},
	                text: {}
	              }
	            }
	          }
	        )
	      end

	    #Indexed fields
		def as_indexed_json(options = nil) 
			self.as_json( only: [ :title, :author, :text, :created_at ] ) 
		end
	end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
	before_action :set_alert, only: [:show]
	
	def new
	  @alert = Alert.new
	end	

	def show		
	end

	def create
	  @alert = Alert.new(alert_params)
	  @alert.last_news = Article.last.id
	  respond_to do |format|
	    if @alert.save
	      format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
	    else
	      format.html { render :new }
	     end
	  end
  	end

	private

    def set_alert
      @alert = Alert.find(params[:id])
    end
    
    def alert_params
      params.require(:alert).permit(:name, :email, :keyword)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order(id: :desc).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author, :text)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def search
	  if params[:q].nil?
	    @articles = []
	  else
	    @articles = Article.search(params[:q]).paginate(:page => params[:page], :per_page => 5)
	 end
	end

end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/alerts/_form.html.erb
<%= form_for @alert, :html => { :class => "form-horizontal alert" } do |f| %>

  <% if @alert.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@alert.errors.count, t(".error")) %> <%= t(".prohibited this alert from being saved") %>:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @alert.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.email_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :keyword, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :keyword, :class => 'form-control' %>
    </div>
    <%=f.error_span(:keyword) %>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-1 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                alerts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/alerts/new.html.erb
<%- model_class = Alert -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/alerts/show.html.erb
<%- model_class = Alert -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @alert.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @alert.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:keyword) %>:</strong></dt>
  <dd><%= @alert.keyword %></dd>
</dl>

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => "form-horizontal article" } do |f| %>

  <% if @article.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@article.errors.count, t(".error")) %> <%= t".prohibited this article from being saved" %>:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, t(".title"), :class => 'control-label col-lg-1' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :author, t(".author"), :class => 'control-label col-lg-1' %>
    <div class="col-lg-10">
      <%= f.text_field :author, :class => 'form-control' %>
    </div>
    <%=f.error_span(:author) %>
  </div>
  <div class="form-group">
    <%= f.label :text, t(".text"), :class => 'control-label col-lg-1' %>
    <div class="col-lg-10">
      <%= f.text_area :text, :class => 'form-control', :rows => '30' %>
    </div>
    <%=f.error_span(:text) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-1 col-lg-10">
      <%= f.submit t('.update', :default => nil), :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">  
  <tbody>
    <% @articles.each do |article| %>
      <tr> 
        <td>
        <h3><%= article.title %></h3>
        <p><label><%= t(".author") %>:</label><%= article.author %></p>
        <p><b><%= I18n.localize article.created_at, format: :long %></b></p>
        <p><%= truncate(article.text, :length => 275, :separator => ' ', :omission => '...')%></p>
       <div class="row">
          <div class="col-md-3 col-md-offset-11">
            <%= link_to t('.show', :default => t("helpers.links.see more")),
            article_path(article),
            :class => 'btn btn-primary btn-xs' %>
          </div>
       </div>
       </td>
      </tr> 
    <% end %>
  </tbody>
</table>
<div class="row">
   <div class="col-md-4 col-md-offset-8">
    <%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
   </div>
</div>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => @article.title  %></h1>
</div>

<table class="table table-striped">  
  <tbody>
      <tr> 
        <td>        
        <p><label><%= t(".author") %>:</label><%= @article.author %></p>
        <p><b><%= I18n.localize @article.created_at, format: :long %></b></p>
        <p><%= @article.text %></p>       
       </td>
      </tr>
  </tbody>
</table>

<%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t(".klipbox news") %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= nav_bar brand: t("helpers.brand.news klipbox"), brand_link: articles_path, fixed: :top, responsive: true do%>
		<%= menu_group do %>
	        <%= menu_item t('.new', :default => t("helpers.links.new")), new_article_path %>
	        <%= menu_item t('.alert', :default => t("helpers.links.alert")), new_alert_path %>
	        <%=form_tag search_path,{:method=>'get', class:"navbar-form navbar-left", role:"search"}  do%>
     		<div class="form-group">
        		<%=text_field_tag :q, params[:q], class:"form-control", :placeholder => t("helpers.placeholder.search")%>
     		</div>
    			<%=submit_tag t("helpers.placeholder.search") ,class:"btn btn-default "%>
			 <%end%>
    	<% end %>		
	<% end %>
	
	<div class="container">
			<%= yield %>
	</div>
</body>
</html>

app/views/search/search.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => 'Search Results' %> (<%= @articles.results.total %>)</h1>
</div>
<% @articles.each do |article| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><%= link_to article.try(:highlight).try(:title) ? article.highlight.title[0].html_safe : article.title,
                controller: "articles",
                action: "show",
                id: article.id
            %>
        </h4>
      </div> 
      <div class="panel-body">
       		<label><%= t(".author") %>: </label> <%=article.author%><br>
            <label><%= t(".date") %>: </label> 
             <% date = DateTime.parse(article.created_at) %>
             <b><%= I18n.localize date, format: :long %></b><br>
            <% unless article.highlight.text.nil? %>
              <% article.highlight.text.each do |snippet| %>
                <%= snippet.html_safe %>...                
              <% end %>
            <% else %>
            	<%= truncate(article.text, :length => 275, :separator => ' ', :omission => '...') %>
            <% end %>
      </div>
    </div>
<% end %> 
<br>
<div class="row">
   <div class="col-md-4 col-md-offset-8">
    <%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
   </div>
</div>